### ISSUE TITLE
Not able to get the library to work

### ISSUE THREAD

**Issue by Nyloth9** [AUAUST/lib-js-inertia-adapter-solid#11]
Hello, sorry about wasting your time, but for the life of me I cant get this to work.

I've made a new project with 
`npx degit solidjs/templates/js my-app`

then i added 
`npm i @auaust/inertia-adapter-solid`

changed the `index.tsx` file to:

```
import { createInertiaApp } from "@auaust/inertia-adapter-solid";
import { render } from "solid-js/web";

createInertiaApp({
  id: "root",
  resolve(name) {
    const pages = import.meta.glob("./Pages/**/*.jsx", { eager: true });
    return pages[`./Pages/${name}.jsx`];
  },
  setup({ el, App, props }) {
    render(() => <App {...props} />, el);
  },
});
```

added a Pages folder in the same folder and made a `Welcome.jsx` file;

```
export default function Welcome() {
    return (
        <div>
        <h1>Welcome to my app!</h1>
        </div>
    );
 }
```
    
and in the console i get error:
```
Uncaught SyntaxError: The requested module '/node_modules/deepmerge/dist/cjs.js?v=0f224227'
does not provide an export named 'default'
```

**Comment by apademide** [comment]
Yeah Inertia with Solid is somewhat of a pain to setup. Lucky you, I had to fix the same issue yesterday 😄 

As the error states, the CJS module `deepmerge` is being imported as `default` which fails. The importing module is `@inertiajs/core`, and by my investigation `deepmerge` isn't even used so I quite don't understand what's up myself.

Anyway, the workaround I came up with is to explicitly tell Vite to optimise `@inertiajs/core`. I couldn't tell you if it ends up tree-shaking the unused import or converting it to a valid MJS module, but it did the trick for me:

`vite.config.ts`
```ts
export default defineConfig({
  // ...
  optimizeDeps: {
    include: ["@inertiajs/core"],
  }
});
```

**Comment by Nyloth9** [comment]
Thank you for the very fast reply. However now i'm getting a new error:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'layout')
    at extractLayouts (dev.jsx:28:28)
    at App (dev.jsx:38:14)
    at chunk-FVPZWHC4.js?v=a57aecf6:599:14
    at untrack (chunk-FVPZWHC4.js?v=a57aecf6:484:12)
    at Object.fn (chunk-FVPZWHC4.js?v=a57aecf6:595:11)
    at runComputation (chunk-FVPZWHC4.js?v=a57aecf6:761:22)
    at updateComputation (chunk-FVPZWHC4.js?v=a57aecf6:740:3)
    at devComponent (chunk-FVPZWHC4.js?v=a57aecf6:610:3)
    at createComponent (chunk-FVPZWHC4.js?v=a57aecf6:1330:10)
    at index.tsx:11:12
```

This is the same error I was getting with the `iksaku/inertia-adapter-solid`.

I was even somehow able to get past that, I dont remember how, but then I was getting the error that 
```
resolve(name) {
    const pages = import.meta.glob("./Pages/**/*.jsx", { eager: true });
    return pages[`./Pages/${name}.jsx`];
  },
```
wasn't passing any `name` argument.

It's such a pain to setup

**Comment by apademide** [comment]
Ah it might be an implementation issue, could you please try setting the `layout` property on the page component returned by ˋresolveˋ to a component. 

```tsx
resolve(name) {
    const pages = import.meta.glob("./Pages/**/*.jsx", { eager: true });
    const page = pages[`./Pages/${name}.jsx`];

    page.layout = (props) => <>{props.children}</>;
    return page;
  },
```

**Comment by Nyloth9** [comment]
Nope, I updated to 0.4.4. and made the code change but im getting the same error:

```
index.tsx:10 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'layout')
    at resolve (index.tsx:10:10)
    at resolveComponent (dev.jsx:103:54)
    at createInertiaApp (dev.jsx:109:29)
    at index.tsx:4:1
```

**Comment by apademide** [comment]
My bad, I misread the first error. ` TypeError: Cannot read properties of null (reading 'layout')` means that your resolver doesn't return a component. So the actual workaround would be in the taste of 
```ts
resolve(name) {
    const pages = import.meta.glob("./Pages/**/*.jsx", { eager: true });
    return pages[`./Pages/${name}.jsx`] ?? () => `Component not found: ${name}`
},
```

I just pushed version `0.4.5` which now handles receiving `null` or `undefined` from `resolve`, providing a fix to the `Cannot read properties of null (reading 'layout')` error.

**Comment by Nyloth9** [comment]
I'm still getting the error with the new version.

I also expanded the resolver to this:

```
  resolve(name) {
    console.log("name", name);
    const pages = import.meta.glob("./Pages/**/*.jsx", { eager: true });
    const page = pages[`./Pages/${name}.jsx`];

    page.layout = (props) => <>{props.children}</>;
    return page;
  },
```

to see if I will log the name, however the logs are:

```
name undefined
index.tsx:11 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'layout')
    at resolve (index.tsx:11:10)
    at resolveComponent (dev.jsx:104:54)
    at createInertiaApp (dev.jsx:110:29)
    at index.tsx:4:1
```

and then when i delete the line `page.layout = (props) => <>{props.children}</>;` the logs are:

```
name undefined
@inertiajs_core.js?v=7c2d84eb:5256 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at F.handleInitialPageVisit (@inertiajs_core.js?v=7c2d84eb:5256:19)
    at F.init (@inertiajs_core.js?v=7c2d84eb:5245:271)
    at App (dev.jsx:47:12)
    at chunk-FVPZWHC4.js?v=f8a54b7f:599:14
    at untrack (chunk-FVPZWHC4.js?v=f8a54b7f:484:12)
    at Object.fn (chunk-FVPZWHC4.js?v=f8a54b7f:595:11)
    at runComputation (chunk-FVPZWHC4.js?v=f8a54b7f:761:22)
    at updateComputation (chunk-FVPZWHC4.js?v=f8a54b7f:740:3)
    at devComponent (chunk-FVPZWHC4.js?v=f8a54b7f:610:3)
    at createComponent
```

**Comment by apademide** [comment]
`TypeError: Cannot set properties of undefined (setting 'layout')` is expected to be thrown by `page.layout = (props) => <>{props.children}</>;` if `const page = pages[`./Pages/${name}.jsx`];` is undefined.

https://github.com/AUAUST/lib-js-inertia-adapter-solid/issues/11#issuecomment-2548638088 is expected to fix your new error, as it'd ensure the resolver always return a component.

**Comment by Nyloth9** [comment]
For me it doesnt return a component because I get an error:

```
@inertiajs_core.js?v=7c2d84eb:5256 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at F.handleInitialPageVisit (@inertiajs_core.js?v=7c2d84eb:5256:19)
    at F.init (@inertiajs_core.js?v=7c2d84eb:5245:271)
    at App (dev.jsx:47:12)
    at chunk-FVPZWHC4.js?v=f8a54b7f:599:14
    at untrack (chunk-FVPZWHC4.js?v=f8a54b7f:484:12)
    at Object.fn (chunk-FVPZWHC4.js?v=f8a54b7f:595:11)
    at runComputation (chunk-FVPZWHC4.js?v=f8a54b7f:761:22)
    at updateComputation (chunk-FVPZWHC4.js?v=f8a54b7f:740:3)
    at devComponent (chunk-FVPZWHC4.js?v=f8a54b7f:610:3)
    at createComponent 
```

Maybe you could try to do the same setup as me and see if it works for you from a fresh project. I dont know what else to try

**Comment by apademide** [comment]
Which version of Inertia are you using? 

Inertia released 2.0 a few days ago and I didn't test it yet. Might be the fix to use 1.3.0

**Comment by Nyloth9** [comment]
It is 1.3.0. 

I think I'm just dumb. I don't think it works without a server framework no? So in my case just installing a npx solid template will not and should not work. I will try to set it up with elixir phoenix as was my original plan. I will come back to you then.

**Comment by apademide** [comment]
Yes, a server runtime is required as the frontend Inertia side renders what the backend tells it to render. Don't hesitate to open another issue if you need help when you have a backend instance. I wouldn't be able to help on the backend side tho.
